# Generated by Django 4.0.2 on 2022-05-01 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProgrammingChallenges',
            new_name='ProgrammingChallenge',
        ),
    ]
