# Generated by Django 4.0.2 on 2022-06-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='push_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
