# Generated by Django 4.0.2 on 2022-06-30 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_push_notifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_active',
            new_name='currently_active',
        ),
    ]
