# Generated by Django 4.0.2 on 2022-07-07 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_is_active_profile_currently_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='push_notifications',
            new_name='is_in_session',
        ),
    ]
