# Generated by Django 4.0.2 on 2022-07-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_push_notifications_profile_is_in_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='in_waiting_room',
            field=models.BooleanField(default=False),
        ),
    ]
