# Generated by Django 4.0.2 on 2022-10-19 22:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile_in_waiting_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='connected_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
