# Generated by Django 4.1.3 on 2023-01-17 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('counter', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.TextField()),
            ],
        ),
    ]
